version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Agro_Market
      POSTGRES_USER: user4
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db

volumes:
  pgdata:
