# Generated by Django 5.1.2 on 2025-04-27 20:32

import django.db.models.deletion
import django.utils.timezone
import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('contraseña', models.TextField()),
                ('tipo_usuario', models.CharField(choices=[('Agricultor', 'Agricultor'), ('Consumidor', 'Consumidor'), ('Empresa', 'Empresa')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAgricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('ubicacion', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.categoria')),
                ('usuario', models.ForeignKey(limit_choices_to={'tipo_usuario': 'Agricultor'}, on_delete=django.db.models.deletion.CASCADE, to='marketplace.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('ubicacion', models.TextField()),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.categoria')),
                ('usuario', models.ForeignKey(limit_choices_to={'tipo_usuario': 'Empresa'}, on_delete=django.db.models.deletion.CASCADE, to='marketplace.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.TextField()),
                ('producto_agricultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.productoagricultor')),
                ('producto_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.productoempresa')),
            ],
        ),
        migrations.CreateModel(
            name='Separacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_separacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField(default=marketplace.models.default_fecha_expiracion)),
                ('producto_agricultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.productoagricultor')),
                ('producto_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.productoempresa')),
                ('consumidor', models.ForeignKey(limit_choices_to={'tipo_usuario': 'Consumidor'}, on_delete=django.db.models.deletion.CASCADE, to='marketplace.usuario')),
            ],
        ),
    ]
