# Generated by Django 5.1.2 on 2025-05-19 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_imagenproducto_url_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='marketplace.productoempresa'),
        ),
    ]
