# Generated by Django 5.1.2 on 2025-05-24 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_imagenproducto_producto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto_agricultor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='marketplace.productoagricultor'),
        ),
    ]
